#define QUAGMIRE_TOOLS          1
#define QUAGMIRE_SLOWCHECKS     1
#define QUAGMIRE_MEMPROFILE     0

#define GL_GLEXT_PROTOTYPES
#define GLEW_STATIC
#define GLEW_NO_GLU
#define NANOVG_GL3_IMPLEMENTATION
#define WIN32_LEAN_AND_MEAN

#define _VERTEX_
#define _TESS_CONTROL_
#define _TESS_EVAL_
#define _GEOMETRY_
#define _FRAGMENT_
